[package]
name = "emunes"
version = "0.1.0"
authors = ["Frederik De Bleser <frederik@debleser.be>", "Michael Smith <m@michaelsmith.be>"]

[dependencies]
bitflags = "1.0.1"

[dependencies.sdl2]
version = "0.31.0"
features = ["ttf"]
